version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50001:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS="--httpPort=-1 --httpsPort=8080"
    command: >
      bash -c "apt-get update && 
      apt-get install -y nodejs npm && 
      npm install -g npm@latest && 
      /sbin/tini -- /usr/local/bin/jenkins.sh"

volumes:
  jenkins_home: 